# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
# change to wherever solution file actually is
# I think this is already pointing to the correct location
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: $(solution)

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    zipAfterPublish: true
    publishWebProjects: true


- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'connectionforproject'
    appType: 'webApp'
    WebAppName: 'sineshop1'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'